### PR TITLE
WIP - run pylint

### PR DESCRIPTION
**Pull request by staubina**

### CODE REVIEW

**Comment by staubina** [comment]
@feanil or @edx/devops Is there anything else needed here for Pylint integration?

**Comment by staubina** [comment]
@nedo Please take a look at the results of these tests.  In another PR I would like to clean all of the pylint and pep8 errors up. It should probably be the next PR we merge after this one.  All the suggestions should be straight forward. Let me know if they are not.

@MirzaMubasharBaig

**Comment by staubina** [comment]
@nedo Please consider the following changes

1. Restructure the repo in the following way
```
- edx-app-test # (new folder)
-- __init__.py
-- android
-- ios 
-- common
-- testdata
-- conftest.py
-- input_data.py

- .gitignore
- .pep8
- .travis.yml
- LICENSE
- pylintrc
- README.md
- requirements.txt
- test-requirements.txt

```

**Comment by staubina** [comment]
I need to look at why I am getting so many import errors in the code, but pylint is running in this PR.

**Comment by nedo** [comment]
Its interesting @staubina, thanks for making it. I'm looking into it. Plus about import errors, I also got these when reviewing my code through pylint internally, I'll figure it out.

**Comment by raeeschachar** [comment]
@staubina I think yes.

**Comment by feanil** [comment]
@staubina we don't really manage pylint, but I assume you're building on top of https://github.com/edx/edx-lint

**Comment by nedbat** [comment]
This does not seem to be using edx-lint.

**Comment by staubina** [comment]
@feanil and @nedbat I copied the pylint from ecommerce.  I was not aware of edx-lint will take a look and adjust accordingly. Thank you.

**Comment by nedo** [comment]
@staubina off course, lets merge it(after edx-lint integration as discussed above), and I'll create separate PR to handle Pylint & Pep8 recommendations. 

I've following 2 points in mind,
 
1. About import errors(Unable to import .... (import-error)), probably we need to see specific rule of Pylint(pylintrc file), because I am not getting import errors when I review project internally through Pylint. Looking forward to edx-lint integration may be it will get fix after that 

2. Travis Job is hooked with master branch for now. Can I do something to create job(s) at feature branch level as well to catch things early ? - This is something not related to this PR just wanted to share that thought 

wdyt ?

**Comment by staubina** [comment]
@nedbat @feanil I used edx-lint to generate the pylintrc file.  Was there more that was needed for that work?  I attempted to follow the README file.

**Comment by staubina** [comment]
@nedo The results are much more manageable now. Once I get the last tweaks in I think we can merge this and start cleaning up the code to pass

**Comment by staubina** [comment]
Ok, This PR is ready to merge and we can start cleaning up these issues in another PR.

**Comment by nedo** [comment]
@staubina the new changes looks good, we can merge this PR

**Pull request merged**
