### PR TITLE
Automate test execution process

### PR DESCRIPTION
**Pull request by nedo**
**Purpose**
Automate test execution process, which will, 
- setup virtual environment 
- trigger execution in needed sequence

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @nedo! I've created [OSPR-5651](https://openedx.atlassian.net/browse/OSPR-5651) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@nedo Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

**Comment by natabene** [comment]
@nedo Please let me know if you need help signing the agreement. I will be happy to answer your questions.

**Comment by natabene** [comment]
@nedo Are you committing this PR on behalf of your employer, or is this a product of your own work, in your own time, and not associated with your employer?

**Comment by nedo** [comment]
Hi @natabene I wanted to commit this PR on the behalf of my employer(Arbisoft).

**Comment by natabene** [comment]
@nedo Thanks, you should be all set now. @miankhalid Could you please have a look?

**Comment by miankhalid** [comment]
@natabene sure!

@bilalawan321 can you have a look on this PR and review?

**Review by bilalawan321 — APPROVED** [review]

**Comment by natabene** [comment]
@bilalawan321 Please merge if this is good to merge. Community authors cannot merge.

**Comment by edx-webhook** [comment]
@nedo 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-app-test&entry.867055334=https://github.com/edx/edx-app-test/pull/71&entry.1484655318=https://github.com/nedo&entry.752974735=2021-03-03+12:48&entry.1917517419=2021-05-04+10:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
