### PR TITLE
[BD-6] OEP-18 Compliance and python 3.8

### PR DESCRIPTION
**Pull request by ericfab179**
Ignore pylint warning broad-except.
Update travis file using new requirements.
Update scripts to use new requirements files.
create pip_tools, base, quality, test, tox and travis requirements files.
Add makefile and include upgrade command.
Include requirements files generated using upgrade command.
Remove old requirements files.
Update openedx.yml.
Add python 3.8 to travis tests.

**Reviewers**
- [ ] @awais786 
- [ ] @morenol

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ericfab179! I've created [OSPR-4664](https://openedx.atlassian.net/browse/OSPR-4664) to keep track of it in JIRA, where we prioritize reviews.  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by awais786** [comment]
@jmbowman I dont have merging rights.

**Comment by nedo** [comment]
@awais786 @jmbowman I can merge this PR if needed.

**Comment by jmbowman** [comment]
Just catching up on this; @awais786 , it looks like it needs a rebase now.  @nedo should this repo stay locked down to just the mobile team, or is it ok to give it the standard write access for the push-pull-all edX GitHub team?

**Comment by nedo** [comment]
@jmbowman both other repos of edX Mobile Team [edx-app-android](https://github.com/edx/edx-app-android) & [edx-app-ios](https://github.com/edx/edx-app-ios) don't have push-pull-all access, so I'll follow the same for this repo as well.

**Comment by nedo** [comment]
@awais786 @jmbowman I can merge this PR for you if needed.

**Comment by awais786** [comment]
@nedo i think you can merge this now.

**Comment by edx-webhook** [comment]
@ericfab179 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-app-test&entry.867055334=https://github.com/edx/edx-app-test/pull/56&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-06-06+15:50&entry.1917517419=2020-06-29+11:37&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
